# Etapa de construção
FROM golang:1.22.4 AS builder
WORKDIR /app
COPY ./src/go.mod ./src/go.sum ./
RUN go mod download
COPY ./src/. .
RUN go build -o main .
RUN chmod +x main
# lista os arquivos cópiados durante a etapa de construção para verificar 
# se todos os arquivos foram transferidos com sucesso para o contêiner.
RUN ls -l /app  # Listar arquivos na etapa de construção

# Etapa final
FROM alpine:latest
RUN apk --no-cache add libc6-compat
WORKDIR /app

# COPY --from=builder /app/main .
# Copia o executável main da etapa anterior (builder) para o diretório 
# /app no contêiner atual. Isso traz o binário compilado do código Go 
# para dentro da imagem final.
COPY --from=builder /app/main .

# lista os arquivos cópiados para dentro do main para assim verificar se tudo está certinho
# RUN ls -l /app 
CMD ["./main"]
