/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String INTER_BLACK = 'Inter-Black';
  static const String INTER_BOLD = 'Inter-Bold';
  static const String INTER_EXTRABOLD = 'Inter-ExtraBold';
  static const String INTER_EXTRALIGHT = 'Inter-ExtraLight';
  static const String INTER_LIGHT = 'Inter-Light';
  static const String INTER_MEDIUM = 'Inter-Medium';
  static const String INTER_REGULAR = 'Inter-Regular';
  static const String INTER_SEMIBOLD = 'Inter-SemiBold';
  static const String INTER_THIN = 'Inter-Thin';
  static const String ROBOTO_BLACK = 'Roboto-Black';
  static const String ROBOTO_BLACKITALIC = 'Roboto-BlackItalic';
  static const String ROBOTO_BOLD = 'Roboto-Bold';
  static const String ROBOTO_BOLDITALIC = 'Roboto-BoldItalic';
  static const String ROBOTO_ITALIC = 'Roboto-Italic';
  static const String ROBOTO_LIGHT = 'Roboto-Light';
  static const String ROBOTO_LIGHTITALIC = 'Roboto-LightItalic';
  static const String ROBOTO_MEDIUM = 'Roboto-Medium';
  static const String ROBOTO_MEDIUMITALIC = 'Roboto-MediumItalic';
  static const String ROBOTO_REGULAR = 'Roboto-Regular';
  static const String ROBOTO_THIN = 'Roboto-Thin';
  static const String ROBOTO_THINITALIC = 'Roboto-ThinItalic';
}
