version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3100:3100"
    volumes:
      - .:/app
    command: npm run dev
