services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest-app
    depends_on:
      - redis
    ports:
      - "3100:3100"
    volumes:
      - .:/app
    command: npm run dev
